### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by polly0296** [polly0296/furima-36237#21]
#URL
https://furima-36237.herokuapp.com/

#Basic認証のIDとパスワード
BASIC_AUTH_USER='admin'
BASIC_AUTH_PASSWORD='2222'

#出品者用のメールアドレスとパスワード
test@example
test12

#購入者用のメールアドレスとパスワード
sample@example
sample12

**Comment by takumi0530** [comment]
@polly0296 さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/128988036-4a390b72-19f3-45bb-9e7d-0b3970355bf2.png)
